# pymaid
installation: pip3 install python-catmaid

In [2]:
%pip install "nbformat>=4.2.0"

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import pandas as pd
from matplotlib import pyplot as plt
from pyvis.network import Network
import networkx as nx

In [2]:
import pymaid

catmaid_url = 'https://l1em.catmaid.virtualflybrain.org'
http_user = None
http_password = None
project_id = 1

rm = pymaid.CatmaidInstance(catmaid_url, http_user, http_password, project_id)

d:\Iliuha_projects\neurosci\bbab\Drosophila-Larvae-Simulation\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
INFO  : Global CATMAID instance set. Caching is ON. (pymaid)


In [3]:
# Получить нейрон по skeleton ID
neuron = pymaid.get_neuron(18440675)
print(neuron)

type                     CatmaidNeuron
name            BAmas12 midline 3 left
id                            18440675
n_nodes                           2974
n_connectors                       193
n_branches                         114
n_leafs                            118
cable_length              371156.40625
soma                        [13820156]
units                      1 nanometer
dtype: object


In [ ]:
neuron.plot3d(connectors = True)

INFO  : Using "plotly" backend for 3D plotting. (navis)
d:\Iliuha_projects\neurosci\bbab\Drosophila-Larvae-Simulation\.venv\Lib\site-packages\navis\plotting\plotly\graph_objs.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for j, this_cn in connectors.groupby("type"):


In [4]:
import navis


#volumes = pymaid.get_volume()['id']
#volumes = [pymaid.get_volume(ids) for ids in volumes]

In [5]:
a = pymaid.get_neuron(29)
b = pymaid.get_neuron(9469519)

In [9]:
navis.plot3d([a, b], connectors = True)

d:\Iliuha_projects\neurosci\bbab\Drosophila-Larvae-Simulation\.venv\Lib\site-packages\navis\plotting\plotly\graph_objs.py:220: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

d:\Iliuha_projects\neurosci\bbab\Drosophila-Larvae-Simulation\.venv\Lib\site-packages\navis\plotting\plotly\graph_objs.py:220: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.



In [10]:

#navis.plot3d(volumes, alpha=0.5, linewidth=0.5)


In [6]:
pymaid.get_node_details(neuron)

node_id                    creation_time creator  \
0       757906 2012-10-08 20:48:44.218000+00:00       5   
1      1298178 2012-11-02 18:51:02.421000+00:00       5   
2      1299545 2012-11-02 19:02:04.914000+00:00       5   
3      1299561 2012-11-02 19:02:05.907000+00:00       5   
4      1299617 2012-11-02 19:02:17.075000+00:00       5   
...        ...                              ...     ...   
3157  24594647 2017-10-24 20:45:07.024000+00:00      72   
3158  24594648 2017-10-24 20:45:08.645000+00:00      72   
3159  24655625 2017-11-02 20:01:05.110000+00:00      72   
3160  24714315 2017-11-09 20:01:59.113000+00:00      74   
3161  62399235 2019-10-25 07:04:26.398000+00:00      72   

                         edition_time editor reviewers review_times  
0    2023-03-15 15:06:23.105778+00:00     18        []           []  
1    2023-03-15 15:06:23.105778+00:00     56        []           []  
2    2023-03-15 15:06:23.105778+00:00     72        []           []  
3    2023-03-15 15:06:23.105778+00:00     72        []           []  
4    2023-03-15 15:06:23.105778+00:00     56        []           []  
...                               ...    ...       ...          ...  
3157 2023-03-15 15:06:23.105778+00:00     72        []           []  
3158 2023-03-15 15:06:23.105778+00:00     72        []           []  
3159 2023-03-15 15:06:23.105778+00:00     72        []           []  
3160 2023-03-15 15:06:23.105778+00:00     74        []           []  
3161 2023-03-15 15:06:23.105778+00:00     72        []           []  

[3162 rows x 7 columns]

In [7]:
#navis.in_volume(pymaid.get)
neuron.connectors

node_id  connector_id type             x             y        z
0     1437021       1437013    1  67157.398438  68183.398438  33800.0
1     2486347       2486301    1  67168.796875  68563.398438  34500.0
2     2640505       2640485    1  73461.601562  73066.398438  47950.0
3     3000846       1298178    1  65743.796875  69353.796875  34200.0
4     3424682       3424669    1  56042.398438  68601.398438  51450.0
..        ...           ...  ...           ...           ...      ...
188   9911645      24655625    1  68913.000000  70165.101562  39150.0
189  21613145       4502183    1  75026.601562  70178.398438  42750.0
190   4369099      13961660    1  49890.199219  68783.796875  51950.0
191   9910735      14225657    1  49692.601562  68804.703125  52950.0
192   9378148      62399235    0  56798.601562  69832.601562  52000.0

[193 rows x 6 columns]

In [12]:
# Получить аннотации (если они есть)
connectors = pymaid.get_connectors([neuron], 'postsynaptic_to')
connectors

INFO  : Cached data used. Use `pymaid.clear_cache()` to clear. (pymaid)


connector_id        x        y        z  confidence  \
0         1298178  65743.8  69353.8  34200.0           5   
1         1436928  67248.6  68206.2  33450.0           5   
2         1437013  67157.4  68183.4  33800.0           5   
3         2486301  67168.8  68563.4  34500.0           5   
4         2640485  73461.6  73066.4  47950.0           5   
..            ...      ...      ...      ...         ...   
129      24593156  73836.5  68782.5  49250.0           5   
130      24593160  73220.9  68873.7  49250.0           5   
131      24593167  73963.2  68924.4  48750.0           5   
132      24593720  72965.7  71438.1  48000.0           5   
133      24655625  68913.0  70165.1  39150.0           5   

              creation_time               edition_time  tags          type  \
0   2012-11-02 23:51:02.421 2023-03-15 20:06:23.105780   NaN  Postsynaptic   
1   2012-11-12 21:12:09.844 2023-03-15 20:06:23.105780   NaN   Presynaptic   
2   2012-11-12 21:12:21.882 2023-03-15 20:06:23.105780   NaN   Presynaptic   
3   2013-01-19 00:19:13.158 2023-03-15 20:06:23.105780   NaN   Presynaptic   
4   2013-01-31 05:49:23.912 2023-03-15 20:06:23.105780   NaN  Postsynaptic   
..                      ...                        ...   ...           ...   
129 2017-10-25 00:06:53.359 2023-03-15 20:06:23.105780   NaN  Postsynaptic   
130 2017-10-25 00:07:05.310 2023-03-15 20:06:23.105780   NaN  Postsynaptic   
131 2017-10-25 00:07:27.413 2023-03-15 20:06:23.105780   NaN  Postsynaptic   
132 2017-10-25 00:49:02.513 2023-03-15 20:06:23.105780   NaN  Postsynaptic   
133 2017-11-03 01:01:05.110 2023-03-15 20:06:23.105780   NaN   Presynaptic   

    creator editor  
0       NaN    NaN  
1       NaN    NaN  
2       NaN    NaN  
3       NaN    NaN  
4       NaN    NaN  
..      ...    ...  
129     NaN    NaN  
130     NaN    NaN  
131     NaN    NaN  
132     NaN    NaN  
133     NaN    NaN  

[134 rows x 11 columns]

In [13]:
#pymaid.get_nodes_in_volume(volumes[0])
#def save_skeletons(neurons_ids):
#    for ids in neurons_ids:
nodes = neuron.nodes
nodes


node_id  parent_id creator_id             x             y        z  \
0     62742186   11217124         74  78166.000000  33569.800781  47600.0   
1     18972565   19057067          4  29341.099609  33597.300781  41250.0   
2     18972822   19056392          4  24841.599609  30160.599609  38800.0   
3     10805600   10805601          4  30626.099609  33314.601562  49650.0   
4     10936334   10936335         38  30682.199219  33139.800781  49150.0   
...        ...        ...        ...           ...           ...      ...   
5762  11217124   62489732         38  78223.000000  33531.199219  47650.0   
5763  62489732   62489734          6  78188.000000  33542.398438  47750.0   
5764  62489734   62489735          6  78222.000000  33459.601562  47850.0   
5765  62489735   62489736          6  78268.101562  33364.601562  47950.0   
5766  62489736   62489737          6  78219.296875  33223.398438  48000.0   

      radius confidence  type  
0       -1.0          5   end  
1       -1.0          5   end  
2       -1.0          5  slab  
3       -1.0          5  slab  
4       -1.0          5  slab  
...      ...        ...   ...  
5762    -1.0          5  slab  
5763    -1.0          5  slab  
5764    -1.0          5  slab  
5765    -1.0          5  slab  
5766    -1.0          5  slab  

[5767 rows x 9 columns]

In [30]:
#pymaid.get_connectors_between(a, a)
#pymaid.get_paths(b, a)
#pymaid.get_connector_links()
#pymaid.get
251328
#neuron.connectors
#pymaid.get_connector_details(neuron)
G = pymaid.get_partners(a)

INFO  : Fetching connectivity table for 1 neurons (pymaid)
INFO  : Cached data used. Use `pymaid.clear_cache()` to clear. (pymaid)
INFO  : Cached data used. Use `pymaid.clear_cache()` to clear. (pymaid)
INFO  : Done. Found 69 pre-, 87 postsynaptic and 0 gap junction-connected neurons (pymaid)


In [31]:
G

neuron_name skeleton_id num_nodes    relation  29  \
0                      45a PN right     8247451      1975    upstream  14   
1                      67b PN right     8246081      3522    upstream  10   
2                       MBE12 right     3234817      8517    upstream   9   
3    mPN iACT bilateral UPPER right    16795524      6820    upstream   9   
4                       MBE1d right     4414184      6141    upstream   8   
..                              ...         ...       ...         ...  ..   
151                            KC54     8559607      3449  downstream   1   
152                     MBE24a left    12475432      6999  downstream   1   
153                           KC100    11813287      3887  downstream   1   
154   mPN iACT bilateral UPPER left    16795838      6522  downstream   1   
155  mPN iACT bilateral UPPER right    16795524      6820  downstream   1   

    total  
0      14  
1      10  
2       9  
3       9  
4       8  
..    ...  
151     1  
152     1  
153     1  
154     1  
155     1  

[156 rows x 6 columns]

In [15]:
G[G['neuron_name'] == 'MBE11b right']

neuron_name skeleton_id num_nodes    relation 29 total
125  MBE11b right     9469519      4277  downstream  1     1

In [16]:
pymaid.get_connectors_between(a, b)

INFO  : Cached data used. Use `pymaid.clear_cache()` to clear. (pymaid)


connector_id                connector_loc  node1_id  source_neuron  \
0           396  [26664.6, 31346.2, 46850.0]       384             29   

   confidence1 creator1                    node1_loc  node2_id  target_neuron  \
0            5      NaN  [26759.6, 31334.8, 46950.0]   9470642        9469519   

   confidence2 creator2                    node2_loc  
0            5      NaN  [26406.2, 31496.3, 46850.0]

In [17]:
neuron2 = pymaid.get_neuron(["BLP34 lateral right"])

In [18]:
#aa = pymaid.get_neuron(4393049)
#bb = pymaid.get_neuron(15458316)
pymaid.get_connectors_between(15458316, 4393049) # порядок важен, если наоборот, то соединений не будет

INFO  : Cached data used. Use `pymaid.clear_cache()` to clear. (pymaid)


connector_id                connector_loc  node1_id  source_neuron  \
0          9840  [43141.4, 61415.6, 50350.0]      9837       15458316   
1          9840  [43141.4, 61415.6, 50350.0]      9837       15458316   
2      11354415  [39284.4, 60361.1, 46850.0]  11354420       15458316   
3      11354485  [39029.8, 59827.2, 45250.0]  11354490       15458316   
4      14397145  [39227.4, 59922.2, 46850.0]  11354420       15458316   
5      15460405  [39132.4, 59929.8, 46000.0]  15460114       15458316   
6      15461021  [43244.0, 61244.6, 51000.0]  15460709       15458316   
7      15572471  [39037.4, 60043.8, 46350.0]  15460129       15458316   

   confidence1 creator1                    node1_loc  node2_id  target_neuron  \
0            5      NaN  [43282.0, 61362.4, 50350.0]      9846        4393049   
1            5      NaN  [43282.0, 61362.4, 50350.0]      9871        4393049   
2            5      NaN  [39216.0, 60125.5, 46850.0]  61395339        4393049   
3            5      NaN  [39071.6, 59927.9, 45250.0]   5480069        4393049   
4            5      NaN  [39216.0, 60125.5, 46850.0]  15844597        4393049   
5            5      NaN  [39166.2, 60029.0, 46000.0]   5479471        4393049   
6            5      NaN  [43489.1, 61465.0, 50950.0]   5478959        4393049   
7            5      NaN  [39168.5, 60072.3, 46350.0]   5479503        4393049   

   confidence2 creator2                    node2_loc  
0            5      NaN  [42936.2, 61537.2, 50350.0]  
1            5      NaN  [43000.8, 61609.4, 50450.0]  
2            5      NaN  [39389.0, 60356.3, 47000.0]  
3            5      NaN  [39274.9, 59542.2, 45400.0]  
4            5      NaN  [39132.4, 59880.4, 47050.0]  
5            5      NaN  [39018.4, 59591.6, 46050.0]  
6            5      NaN  [43118.6, 60879.8, 50950.0]  
7            5      NaN  [38944.3, 59709.4, 46300.0]

In [19]:
q = pd.read_csv("../../Datasets/Original/ad_connectivity_matrix.csv")
#all_all = q[q.columns[1:]].to_numpy()
q

Unnamed: 0   29  9469519  15458316  4393049  4679139  15592696  \
0             29  0.0      1.0       0.0      0.0      0.0       0.0   
1        9469519  0.0      0.0       0.0      0.0      0.0       0.0   
2       15458316  0.0      0.0       0.0      8.0     15.0       0.0   
3        4393049  0.0      0.0       0.0      0.0      0.0       0.0   
4        4679139  0.0      0.0       0.0      0.0      0.0       0.0   
...          ...  ...      ...       ...      ...      ...       ...   
2947    16362243  0.0      0.0       0.0      0.0      0.0       0.0   
2948    17608754  0.0      0.0       0.0      0.0      0.0       0.0   
2949    17951153  0.0      0.0       0.0      0.0      0.0       0.0   
2950    18679889  0.0      0.0       0.0      0.0      0.0       0.0   
2951    18785124  0.0      0.0       0.0      0.0      0.0       0.0   

      17327188  15653288  10158972  ...  15762568  15914721  15996271  \
0          0.0       0.0       0.0  ...         0         0         0   
1          0.0       0.0       0.0  ...         0         0         0   
2          2.0       0.0       1.0  ...         0         0         0   
3          0.0       0.0       0.0  ...         0         0         0   
4          0.0       0.0       0.0  ...         0         0         0   
...        ...       ...       ...  ...       ...       ...       ...   
2947       0.0       0.0       0.0  ...         0         0         0   
2948       0.0       0.0       0.0  ...         0         0         0   
2949       0.0       0.0       0.0  ...         0         0         0   
2950       0.0       0.0       0.0  ...         0         0         0   
2951       0.0       0.0       0.0  ...         0         0         0   

      15998899  15998913  16362243  17608754  17951153  18679889  18785124  
0            0         0         0         0         0         0         0  
1            0         0         0         0         0         0         0  
2            0         0         0         0         0         0         0  
3            0         0         0         0         0         0         0  
4            0         0         0         0         0         0         0  
...        ...       ...       ...       ...       ...       ...       ...  
2947         0         0         0         0         0         0         0  
2948         0         0         0         0         0         0         0  
2949         0         0         0         0         0         0         0  
2950         0         0         0         0         0         0         0  
2951         0         0         0         0         0         0         0  

[2952 rows x 2953 columns]

In [20]:
q[q['Unnamed: 0'] == neuron2.id]

Empty DataFrame
Columns: [Unnamed: 0, 29, 9469519, 15458316, 4393049, 4679139, 15592696, 17327188, 15653288, 10158972, 12842593, 3844799, 37365, 8700125, 9927082, 40045, 8877971, 5030808, 7865652, 7941652, 8980589, 8274902, 15587166, 10263287, 15567466, 12335381, 3946166, 16751955, 7160160, 17698681, 17360038, 17165429, 5865628, 17360254, 16490014, 5691934, 10609443, 1690576, 6723364, 11263687, 12325227, 16594752, 7766016, 2772093, 3009700, 9530532, 18639459, 11271082, 8979434, 14762026, 11081239, 1347886, 19470184, 15983225, 17951049, 2432564, 15995404, 9589146, 1375101, 17176866, 3436420, 4523584, 10202724, 16911458, 4595609, 19120772, 15983156, 12740290, 3915835, 19017854, 7568455, 8124177, 7897051, 8480418, 7874184, 8717219, 8247641, 8270683, 2775707, 7555968, 2512602, 2775943, 9539868, 8271034, 7555204, 8447845, 2544902, 2532841, 7566199, 900032, 1856512, 3865952, 8199671, 6557581, 8245869, 8198317, 15997929, 3736500, 13380660, 15681740, ...]
Index: []

[0 rows x 2953 columns]

In [21]:
#pd.unique(nodes['type'])
nodes[nodes['type'] == 'end']

node_id  parent_id creator_id             x             y        z  \
0     62742186   11217124         74  78166.000000  33569.800781  47600.0   
1     18972565   19057067          4  29341.099609  33597.300781  41250.0   
66    11081353   11081352         38  68415.500000  38763.000000  50650.0   
142   11081472   11081471         38  70937.500000  37635.199219  51650.0   
168   11081624   11081622         38  70629.601562  36898.000000  51000.0   
...        ...        ...        ...           ...           ...      ...   
5744  21453998   21453997          6  29508.900391  29212.500000  37400.0   
5749  21454002    8856729          6  30185.300781  28133.300781  37800.0   
5753  21454006   21454005          6  30971.900391  29431.000000  39000.0   
5758  21454011   21454010          6  31226.500000  30021.900391  39100.0   
5759  21454012   21454009          6  30852.199219  30080.800781  39100.0   

      radius confidence type  
0       -1.0          5  end  
1       -1.0          5  end  
66      -1.0          5  end  
142     -1.0          5  end  
168     -1.0          5  end  
...      ...        ...  ...  
5744    -1.0          5  end  
5749    -1.0          5  end  
5753    -1.0          5  end  
5758    -1.0          5  end  
5759    -1.0          5  end  

[262 rows x 9 columns]

In [22]:
import numpy as np
def get_matrix(nodes):    
    node_id = pd.unique(nodes['node_id'])
    parents = pd.unique(nodes['parent_id'])
    all_nodes = list(set(node_id) | set(parents))
    matrix = np.zeros([len(all_nodes), len(all_nodes)], np.int8)
    keys = {idt:ind for ind, idt in enumerate(all_nodes)}
    for idt, parent in zip(nodes['node_id'], nodes['parent_id']):
        node_ind = keys[idt]
        parent_ind = keys[parent]
        matrix[node_ind][parent_ind] = 1
    return matrix, keys


def simplify_directed_graph(adj_matrix):
    if not isinstance(adj_matrix, np.ndarray) or adj_matrix.shape[0] != adj_matrix.shape[1]:
        raise ValueError("Входные данные должны быть квадратной матрицей numpy.")
    
    if adj_matrix.shape[0] == 0:
        return np.array([])

    G = nx.from_numpy_array(adj_matrix, create_using=nx.DiGraph)

    while True:
        # Находим все вершины с in-degree=1 и out-degree=1
        nodes_to_remove = [
            node for node in G.nodes() 
            if G.in_degree(node) == 1 and G.out_degree(node) == 1
        ]
        
        if not nodes_to_remove:
            break # Если таких вершин нет, завершаем

        for node in nodes_to_remove:
            # Если узел уже был удален на предыдущей итерации этого же цикла, пропускаем
            if node not in G: 
                continue

            # Получаем единственного предшественника и преемника
            # NetworkX гарантирует, что list(predecessors/successors) вернет один элемент,
            # если степень равна 1.
            u = list(G.predecessors(node))[0]
            v = list(G.successors(node))[0]
            
            # Добавляем новое ребро, если оно не существует и не является петлей
            if not G.has_edge(u, v) and u != v:
                G.add_edge(u, v)
            
            G.remove_node(node)
             
    # Преобразуем упрощенный граф обратно в матрицу смежности
    if G.number_of_nodes() == 0:
        return np.array([])
    else:
        return nx.to_numpy_array(G, nodelist=sorted(list(G.nodes())))

# def get_optimizations(ind, matrix, ind_to_eq:set, moved = None, non_connected = None):
#     if moved is None:
#         moved = []
#     if non_connected is None:
#         non_connected = []
#     if ind in moved:
#         return
#     moved.append(ind)
#     parents = [i for i, c in enumerate(matrix[ind]) if c]
#     if len(parents) == 1:
#         ind_to_eq.add((ind, parents[0]))
#     elif len(parents) == 0:
#         non_connected.append(ind)
#         return non_connected
# 
#     return sum((get_optimizations(p, matrix, ind_to_eq, moved) for p in parents), [])
# 
# def optimize(table):
#     ind_to_eq = set()
#     non_connected = get_optimizations(0, table, ind_to_eq)
#     q = list(ind_to_eq)
#     G = []
#     lr = {h[0]:h[1] for h in q}
#     rl = {h[1]:h[0] for h in q}
#     for ha in q:
#         a = (ha[0], ha[1])
#     while a[0] in lr:
#         a[0] = lr[a[0]]
#     while a[1] in rl:
#         a[1] = rl[a[1]]

In [23]:

matrix, keys = get_matrix(neuron.nodes)
g = simplify_directed_graph(matrix)
G = nx.from_numpy_array(g)
#plt.imshow(matrix)
#plt.show()
print(g)
print(g.shape)
net = Network(notebook=False, directed=True,)
net.show_buttons(filter_=['physics'])
net.from_nx(G)
net.save_graph('graph.html')

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(520, 520)


In [24]:
pymaid.get_connector_details(connectors)

INFO  : Data for 347 of 347 unique connector IDs retrieved (pymaid)


connector_id presynaptic_to  \
0           9652       22375722   
1         251133       22382540   
2         251328       17360254   
3         251404       17360254   
4         251438       17360254   
..           ...            ...   
342     61430220       10282065   
343     61439936       11081239   
344     61452094       11081239   
345     61536070       17360076   
346     61613785       11081239   

                                       postsynaptic_to presynaptic_to_node  \
0    [16713231, 11081239, 22375747, 22375751, 22375...                9584   
1    [9051500, 17360254, 11081239, 22382544, 22382548]              251130   
2    [8697453, 11081239, 1042538, 14762026, 1098295...              251292   
3    [8805777, 11081239, 22382584, 22382588, 22382592]              251272   
4                       [11081239, 22382596, 22382600]              251278   
..                                                 ...                 ...   
342                                [11081239, 3946166]            19955320   
343                     [15431795, 17328632, 24980001]            10937640   
344                     [12279941, 24981835, 24981839]            61452093   
345                                [3182103, 11081239]            16056803   
346                       [5656152, 5512988, 25010521]             5549125   

                                  postsynaptic_to_node  
0           [9666, 9706, 9658, 9674, 9682, 9690, 9714]  
1             [251139, 251122, 251148, 251156, 251164]  
2    [251334, 251358, 2883597, 3336603, 3336610, 25...  
3           [251434, 19051733, 251410, 251418, 251426]  
4                             [251452, 251444, 251460]  
..                                                 ...  
342                               [11084154, 61430221]  
343                     [61439937, 19696142, 61439938]  
344                     [61452090, 61452095, 61452096]  
345                               [61536066, 16075798]  
346                      [18360155, 5537989, 61613786]  

[347 rows x 5 columns]

In [25]:
# Получить таблицу точек нейрона
nodes = neuron.nodes

# Посмотреть структуру таблицы
print(nodes.head())

# Если есть аннотации или типы ветвей, они будут в столбцах nodes


    node_id  parent_id creator_id             x             y        z  \
0  62742186   11217124         74  78166.000000  33569.800781  47600.0   
1  18972565   19057067          4  29341.099609  33597.300781  41250.0   
2  18972822   19056392          4  24841.599609  30160.599609  38800.0   
3  10805600   10805601          4  30626.099609  33314.601562  49650.0   
4  10936334   10936335         38  30682.199219  33139.800781  49150.0   

   radius confidence  type  
0    -1.0          5   end  
1    -1.0          5   end  
2    -1.0          5  slab  
3    -1.0          5  slab  
4    -1.0          5  slab  


Help on package pymaid:

NAME
    pymaid

PACKAGE CONTENTS
    cache
    client
    cluster
    config
    connectivity
    core
    cytoscape
    fetch (package)
    morpho
    neuron_label
    stack
    tiles
    upload
    user_stats
    utils

DATA
    __version_vector__ = (2, 4, 2)
    logger = <Logger pymaid (INFO)>

VERSION
    2.4.2

FILE
    d:\iliuha_projects\neurosci\bbab\drosophila-larvae-simulation\.venv\lib\site-packages\pymaid\__init__.py



In [26]:
connectors

connector_id        x        y        z  confidence  \
0            9652  22332.6  33455.2  52450.0           5   
1          251133  26109.8  38722.0  51800.0           5   
2          251328  21682.8  40390.2  52900.0           5   
3          251404  22066.6  39896.2  52650.0           5   
4          251438  21565.0  39558.0  52500.0           5   
..            ...      ...      ...      ...         ...   
342      61430220  65490.4  29606.9  41400.0           5   
343      61439936  31110.0  32096.1  41650.0           5   
344      61452094  74311.5  31621.1  47150.0           5   
345      61536070  30325.9  30059.9  38000.0           5   
346      61613785  30480.7  33523.6  44600.0           5   

              creation_time               edition_time tags          type  \
0   2012-08-30 22:47:05.268 2023-03-15 20:06:23.105780  NaN  Postsynaptic   
1   2012-09-13 03:52:52.246 2023-03-15 20:06:23.105780  NaN  Postsynaptic   
2   2012-09-13 03:56:03.257 2023-03-15 20:06:23.105780  NaN   Presynaptic   
3   2012-09-13 03:56:26.305 2023-03-15 20:06:23.105780  NaN   Presynaptic   
4   2012-09-13 03:56:37.339 2023-03-15 20:06:23.105780  NaN   Presynaptic   
..                      ...                        ...  ...           ...   
342 2018-11-30 01:24:20.859 2023-03-15 20:06:23.105780  NaN   Presynaptic   
343 2018-12-03 23:03:27.476 2023-03-15 20:06:23.105780  NaN   Presynaptic   
344 2018-12-05 21:15:47.487 2023-03-15 20:06:23.105780  NaN   Presynaptic   
345 2019-01-03 22:52:42.097 2023-03-15 20:06:23.105780  NaN   Presynaptic   
346 2019-01-24 14:54:29.756 2023-03-15 20:06:23.105780  NaN   Presynaptic   

    creator editor  
0       NaN    NaN  
1       NaN    NaN  
2       NaN    NaN  
3       NaN    NaN  
4       NaN    NaN  
..      ...    ...  
342     NaN    NaN  
343     NaN    NaN  
344     NaN    NaN  
345     NaN    NaN  
346     NaN    NaN  

[347 rows x 11 columns]

In [27]:
#ids = [11081239, 12345678, 87654321]
#connectome = pymaid.connectivity.core.
#print(connectome)