# pymaid
installation: pip3 install python-catmaid

In [23]:
%pip install "nbformat>=4.2.0"

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [24]:
import pandas as pd
from matplotlib import pyplot as plt
from pyvis.network import Network
import networkx as nx

In [25]:
import pymaid

catmaid_url = 'https://l1em.catmaid.virtualflybrain.org'
http_user = None
http_password = None
project_id = 1

rm = pymaid.CatmaidInstance(catmaid_url, http_user, http_password, project_id)

INFO  : Global CATMAID instance set. Caching is ON. (pymaid)


In [26]:
# Получить нейрон по skeleton ID
neuron = pymaid.get_neuron(11081239)
print(neuron)

type                            CatmaidNeuron
name            AF: DPLal BPL-to-medial_right
id                                   11081239
n_nodes                                  5767
n_connectors                              356
n_branches                                257
n_leafs                                   262
cable_length                         620412.5
soma                               [16076928]
units                             1 nanometer
dtype: object


In [27]:
neuron.plot3d(connectors = True)

d:\Iliuha_projects\neurosci\bbab\Drosophila-Larvae-Simulation\.venv\Lib\site-packages\navis\plotting\plotly\graph_objs.py:220: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.



In [ ]:
import navis


#volumes = pymaid.get_volume()['id']
#volumes = [pymaid.get_volume(ids) for ids in volumes]

INFO  : Retrieving list of available volumes. (pymaid)
INFO  : Cached data used. Use `pymaid.clear_cache()` to clear. (pymaid)
INFO  : Cached data used. Use `pymaid.clear_cache()` to clear. (pymaid)
INFO  : Cached data used. Use `pymaid.clear_cache()` to clear. (pymaid)
INFO  : Cached data used. Use `pymaid.clear_cache()` to clear. (pymaid)
INFO  : Cached data used. Use `pymaid.clear_cache()` to clear. (pymaid)
INFO  : Cached data used. Use `pymaid.clear_cache()` to clear. (pymaid)
INFO  : Cached data used. Use `pymaid.clear_cache()` to clear. (pymaid)
INFO  : Cached data used. Use `pymaid.clear_cache()` to clear. (pymaid)
INFO  : Cached data used. Use `pymaid.clear_cache()` to clear. (pymaid)
INFO  : Cached data used. Use `pymaid.clear_cache()` to clear. (pymaid)
INFO  : Cached data used. Use `pymaid.clear_cache()` to clear. (pymaid)
INFO  : Cached data used. Use `pymaid.clear_cache()` to clear. (pymaid)
INFO  : Cached data used. Use `pymaid.clear_cache()` to clear. (pymaid)
INFO  : C

In [ ]:

#navis.plot3d(volumes, alpha=0.5, linewidth=0.5)


In [30]:
#navis.in_volume(pymaid.get)

In [31]:
# Получить аннотации (если они есть)
connectors = pymaid.get_connectors([neuron])
connectors

connector_id        x        y        z  confidence  \
0            9652  22332.6  33455.2  52450.0           5   
1          251133  26109.8  38722.0  51800.0           5   
2          251328  21682.8  40390.2  52900.0           5   
3          251404  22066.6  39896.2  52650.0           5   
4          251438  21565.0  39558.0  52500.0           5   
..            ...      ...      ...      ...         ...   
342      61430220  65490.4  29606.9  41400.0           5   
343      61439936  31110.0  32096.1  41650.0           5   
344      61452094  74311.5  31621.1  47150.0           5   
345      61536070  30325.9  30059.9  38000.0           5   
346      61613785  30480.7  33523.6  44600.0           5   

              creation_time               edition_time tags          type  \
0   2012-08-30 22:47:05.268 2023-03-15 20:06:23.105780  NaN  Postsynaptic   
1   2012-09-13 03:52:52.246 2023-03-15 20:06:23.105780  NaN  Postsynaptic   
2   2012-09-13 03:56:03.257 2023-03-15 20:06:23.105780  NaN   Presynaptic   
3   2012-09-13 03:56:26.305 2023-03-15 20:06:23.105780  NaN   Presynaptic   
4   2012-09-13 03:56:37.339 2023-03-15 20:06:23.105780  NaN   Presynaptic   
..                      ...                        ...  ...           ...   
342 2018-11-30 01:24:20.859 2023-03-15 20:06:23.105780  NaN   Presynaptic   
343 2018-12-03 23:03:27.476 2023-03-15 20:06:23.105780  NaN   Presynaptic   
344 2018-12-05 21:15:47.487 2023-03-15 20:06:23.105780  NaN   Presynaptic   
345 2019-01-03 22:52:42.097 2023-03-15 20:06:23.105780  NaN   Presynaptic   
346 2019-01-24 14:54:29.756 2023-03-15 20:06:23.105780  NaN   Presynaptic   

    creator editor  
0       NaN    NaN  
1       NaN    NaN  
2       NaN    NaN  
3       NaN    NaN  
4       NaN    NaN  
..      ...    ...  
342     NaN    NaN  
343     NaN    NaN  
344     NaN    NaN  
345     NaN    NaN  
346     NaN    NaN  

[347 rows x 11 columns]

In [32]:
#pymaid.get_nodes_in_volume(volumes[0])
#def save_skeletons(neurons_ids):
#    for ids in neurons_ids:
nodes = neuron.nodes
nodes


node_id  parent_id creator_id             x             y        z  \
0     62742186   11217124         74  78166.000000  33569.800781  47600.0   
1     18972565   19057067          4  29341.099609  33597.300781  41250.0   
2     18972822   19056392          4  24841.599609  30160.599609  38800.0   
3     10805600   10805601          4  30626.099609  33314.601562  49650.0   
4     10936334   10936335         38  30682.199219  33139.800781  49150.0   
...        ...        ...        ...           ...           ...      ...   
5762  11217124   62489732         38  78223.000000  33531.199219  47650.0   
5763  62489732   62489734          6  78188.000000  33542.398438  47750.0   
5764  62489734   62489735          6  78222.000000  33459.601562  47850.0   
5765  62489735   62489736          6  78268.101562  33364.601562  47950.0   
5766  62489736   62489737          6  78219.296875  33223.398438  48000.0   

      radius confidence  type  
0       -1.0          5   end  
1       -1.0          5   end  
2       -1.0          5  slab  
3       -1.0          5  slab  
4       -1.0          5  slab  
...      ...        ...   ...  
5762    -1.0          5  slab  
5763    -1.0          5  slab  
5764    -1.0          5  slab  
5765    -1.0          5  slab  
5766    -1.0          5  slab  

[5767 rows x 9 columns]

In [47]:
#pd.unique(nodes['type'])
nodes[nodes['type'] == 'end']

node_id  parent_id creator_id             x             y        z  \
0     62742186   11217124         74  78166.000000  33569.800781  47600.0   
1     18972565   19057067          4  29341.099609  33597.300781  41250.0   
66    11081353   11081352         38  68415.500000  38763.000000  50650.0   
142   11081472   11081471         38  70937.500000  37635.199219  51650.0   
168   11081624   11081622         38  70629.601562  36898.000000  51000.0   
...        ...        ...        ...           ...           ...      ...   
5744  21453998   21453997          6  29508.900391  29212.500000  37400.0   
5749  21454002    8856729          6  30185.300781  28133.300781  37800.0   
5753  21454006   21454005          6  30971.900391  29431.000000  39000.0   
5758  21454011   21454010          6  31226.500000  30021.900391  39100.0   
5759  21454012   21454009          6  30852.199219  30080.800781  39100.0   

      radius confidence type  
0       -1.0          5  end  
1       -1.0          5  end  
66      -1.0          5  end  
142     -1.0          5  end  
168     -1.0          5  end  
...      ...        ...  ...  
5744    -1.0          5  end  
5749    -1.0          5  end  
5753    -1.0          5  end  
5758    -1.0          5  end  
5759    -1.0          5  end  

[262 rows x 9 columns]

In [33]:
import numpy as np
def get_matrix(nodes):    
    node_id = pd.unique(nodes['node_id'])
    parents = pd.unique(nodes['parent_id'])
    all_nodes = list(set(node_id) | set(parents))
    matrix = np.zeros([len(all_nodes), len(all_nodes)], np.int8)
    keys = {idt:ind for ind, idt in enumerate(all_nodes)}
    for idt, parent in zip(nodes['node_id'], nodes['parent_id']):
        node_ind = keys[idt]
        parent_ind = keys[parent]
        matrix[node_ind][parent_ind] = 1
    return matrix, keys


def simplify_directed_graph(adj_matrix):
    if not isinstance(adj_matrix, np.ndarray) or adj_matrix.shape[0] != adj_matrix.shape[1]:
        raise ValueError("Входные данные должны быть квадратной матрицей numpy.")
    
    if adj_matrix.shape[0] == 0:
        return np.array([])

    G = nx.from_numpy_array(adj_matrix, create_using=nx.DiGraph)

    while True:
        # Находим все вершины с in-degree=1 и out-degree=1
        nodes_to_remove = [
            node for node in G.nodes() 
            if G.in_degree(node) == 1 and G.out_degree(node) == 1
        ]
        
        if not nodes_to_remove:
            break # Если таких вершин нет, завершаем

        for node in nodes_to_remove:
            # Если узел уже был удален на предыдущей итерации этого же цикла, пропускаем
            if node not in G: 
                continue

            # Получаем единственного предшественника и преемника
            # NetworkX гарантирует, что list(predecessors/successors) вернет один элемент,
            # если степень равна 1.
            u = list(G.predecessors(node))[0]
            v = list(G.successors(node))[0]
            
            # Добавляем новое ребро, если оно не существует и не является петлей
            if not G.has_edge(u, v) and u != v:
                G.add_edge(u, v)
            
            G.remove_node(node)
            
    # Преобразуем упрощенный граф обратно в матрицу смежности
    if G.number_of_nodes() == 0:
        return np.array([])
    else:
        return nx.to_numpy_array(G, nodelist=sorted(list(G.nodes())))

# def get_optimizations(ind, matrix, ind_to_eq:set, moved = None, non_connected = None):
#     if moved is None:
#         moved = []
#     if non_connected is None:
#         non_connected = []
#     if ind in moved:
#         return
#     moved.append(ind)
#     parents = [i for i, c in enumerate(matrix[ind]) if c]
#     if len(parents) == 1:
#         ind_to_eq.add((ind, parents[0]))
#     elif len(parents) == 0:
#         non_connected.append(ind)
#         return non_connected
# 
#     return sum((get_optimizations(p, matrix, ind_to_eq, moved) for p in parents), [])
# 
# def optimize(table):
#     ind_to_eq = set()
#     non_connected = get_optimizations(0, table, ind_to_eq)
#     q = list(ind_to_eq)
#     G = []
#     lr = {h[0]:h[1] for h in q}
#     rl = {h[1]:h[0] for h in q}
#     for ha in q:
#         a = (ha[0], ha[1])
#     while a[0] in lr:
#         a[0] = lr[a[0]]
#     while a[1] in rl:
#         a[1] = rl[a[1]]

In [34]:

matrix, keys = get_matrix(neuron.nodes)
g = simplify_directed_graph(matrix)
G = nx.from_numpy_array(g)
#plt.imshow(matrix)
#plt.show()
print(g)
print(g.shape)
net = Network(notebook=False, directed=True,)
net.show_buttons(filter_=['physics'])
net.from_nx(G)
net.save_graph('graph.html')

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(520, 520)


In [35]:
pymaid.get_connector_details(connectors)

INFO  : Data for 347 of 347 unique connector IDs retrieved (pymaid)


connector_id presynaptic_to  \
0           9652       22375722   
1         251133       22382540   
2         251328       17360254   
3         251404       17360254   
4         251438       17360254   
..           ...            ...   
342     61430220       10282065   
343     61439936       11081239   
344     61452094       11081239   
345     61536070       17360076   
346     61613785       11081239   

                                       postsynaptic_to presynaptic_to_node  \
0    [16713231, 11081239, 22375747, 22375751, 22375...                9584   
1    [9051500, 17360254, 11081239, 22382544, 22382548]              251130   
2    [8697453, 11081239, 1042538, 14762026, 1098295...              251292   
3    [8805777, 11081239, 22382584, 22382588, 22382592]              251272   
4                       [11081239, 22382596, 22382600]              251278   
..                                                 ...                 ...   
342                                [11081239, 3946166]            19955320   
343                     [15431795, 17328632, 24980001]            10937640   
344                     [12279941, 24981835, 24981839]            61452093   
345                                [3182103, 11081239]            16056803   
346                       [5656152, 5512988, 25010521]             5549125   

                                  postsynaptic_to_node  
0           [9666, 9706, 9658, 9674, 9682, 9690, 9714]  
1             [251139, 251122, 251148, 251156, 251164]  
2    [251334, 251358, 2883597, 3336603, 3336610, 25...  
3           [251434, 19051733, 251410, 251418, 251426]  
4                             [251452, 251444, 251460]  
..                                                 ...  
342                               [11084154, 61430221]  
343                     [61439937, 19696142, 61439938]  
344                     [61452090, 61452095, 61452096]  
345                               [61536066, 16075798]  
346                      [18360155, 5537989, 61613786]  

[347 rows x 5 columns]

In [36]:
# Получить таблицу точек нейрона
nodes = neuron.nodes

# Посмотреть структуру таблицы
print(nodes.head())

# Если есть аннотации или типы ветвей, они будут в столбцах nodes


    node_id  parent_id creator_id             x             y        z  \
0  62742186   11217124         74  78166.000000  33569.800781  47600.0   
1  18972565   19057067          4  29341.099609  33597.300781  41250.0   
2  18972822   19056392          4  24841.599609  30160.599609  38800.0   
3  10805600   10805601          4  30626.099609  33314.601562  49650.0   
4  10936334   10936335         38  30682.199219  33139.800781  49150.0   

   radius confidence  type  
0    -1.0          5   end  
1    -1.0          5   end  
2    -1.0          5  slab  
3    -1.0          5  slab  
4    -1.0          5  slab  


Help on package pymaid:

NAME
    pymaid

PACKAGE CONTENTS
    cache
    client
    cluster
    config
    connectivity
    core
    cytoscape
    fetch (package)
    morpho
    neuron_label
    stack
    tiles
    upload
    user_stats
    utils

DATA
    __version_vector__ = (2, 4, 2)
    logger = <Logger pymaid (INFO)>

VERSION
    2.4.2

FILE
    d:\iliuha_projects\neurosci\bbab\drosophila-larvae-simulation\.venv\lib\site-packages\pymaid\__init__.py



In [37]:
connectors

connector_id        x        y        z  confidence  \
0            9652  22332.6  33455.2  52450.0           5   
1          251133  26109.8  38722.0  51800.0           5   
2          251328  21682.8  40390.2  52900.0           5   
3          251404  22066.6  39896.2  52650.0           5   
4          251438  21565.0  39558.0  52500.0           5   
..            ...      ...      ...      ...         ...   
342      61430220  65490.4  29606.9  41400.0           5   
343      61439936  31110.0  32096.1  41650.0           5   
344      61452094  74311.5  31621.1  47150.0           5   
345      61536070  30325.9  30059.9  38000.0           5   
346      61613785  30480.7  33523.6  44600.0           5   

              creation_time               edition_time tags          type  \
0   2012-08-30 22:47:05.268 2023-03-15 20:06:23.105780  NaN  Postsynaptic   
1   2012-09-13 03:52:52.246 2023-03-15 20:06:23.105780  NaN  Postsynaptic   
2   2012-09-13 03:56:03.257 2023-03-15 20:06:23.105780  NaN   Presynaptic   
3   2012-09-13 03:56:26.305 2023-03-15 20:06:23.105780  NaN   Presynaptic   
4   2012-09-13 03:56:37.339 2023-03-15 20:06:23.105780  NaN   Presynaptic   
..                      ...                        ...  ...           ...   
342 2018-11-30 01:24:20.859 2023-03-15 20:06:23.105780  NaN   Presynaptic   
343 2018-12-03 23:03:27.476 2023-03-15 20:06:23.105780  NaN   Presynaptic   
344 2018-12-05 21:15:47.487 2023-03-15 20:06:23.105780  NaN   Presynaptic   
345 2019-01-03 22:52:42.097 2023-03-15 20:06:23.105780  NaN   Presynaptic   
346 2019-01-24 14:54:29.756 2023-03-15 20:06:23.105780  NaN   Presynaptic   

    creator editor  
0       NaN    NaN  
1       NaN    NaN  
2       NaN    NaN  
3       NaN    NaN  
4       NaN    NaN  
..      ...    ...  
342     NaN    NaN  
343     NaN    NaN  
344     NaN    NaN  
345     NaN    NaN  
346     NaN    NaN  

[347 rows x 11 columns]

In [38]:
#ids = [11081239, 12345678, 87654321]
#connectome = pymaid.connectivity.core.
#print(connectome)